name: builds

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  build-windows:
    runs-on: windows-2022
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
          call tests.bat
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build
        shell: bash
        run: |
          chmod +x cb.sh
          chmod +x tests.sh
          ./tests.sh